name: collection

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.18", "1.19"]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile=coverage.out

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        